sudo: required

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)

before_install:
  - docker build -t franciscoserrano/metegol-project-test -f ./Dockerfile.dev

script:
  - docker run franciscoserrano/metegol-project-test mvn test

after_success:
  - docker build -t franciscoserrano/metegol-project:latest -t franciscoserrano/metegol-project:$SHA .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push franciscoserrano/metegol-project:latest
  - docker push franciscoserrano/metegol-project:$SHA