sudo: required

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)

before_install:
  - make build-test

script:
  - make run-test

after_success:
  - docker build -t franciscoserrano/metegol-project:latest -t franciscoserrano/metegol-project:$SHA .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push franciscoserrano/metegol-project:latest
  - docker push franciscoserrano/metegol-project:$SHA