language: java
sudo: required

services:
  - docker

cache:
  directories:
    - "$HOME/.m2"

env:
  global:
    - SHA=$(git rev-parse HEAD)

before_cache:
  - rm -rf $HOME/.m2/repository/com/autentia/traviscodacy

before_install:
  - chmod +x mvnw
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
  - docker build -t franciscoserrano/metegol-project-test -f ./Dockerfile.dev .

script:
  - docker run franciscoserrano/metegol-project-test mvn test
  - mvn jacoco:report

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/jacoco/jacoco.xml
  - docker build -t franciscoserrano/metegol-project:latest -t franciscoserrano/metegol-project:$SHA .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push franciscoserrano/metegol-project:latest
  - docker push franciscoserrano/metegol-project:$SHA