language: java
sudo: required

services:
  - docker

cache:
  directories:
    - "$HOME/.m2"

env:
  global:
    - SHA=$(git rev-parse HEAD)

before_cache:
  - rm -rf $HOME/.m2/repository/com/autentia/traviscodacy

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
  - make build-test

script:
  - make run-test

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/jacoco/jacoco.xml
  - make build-deploy